const products=[
{id:'SR-001',name:'The Quiet Path',category:'Spirituality',price:499,author:'Aarav Mehta',stock:12},
{id:'SR-002',name:'Letters to Tomorrow',category:'Self Help',price:399,author:'Mira Shah',stock:18},
{id:'SR-003',name:'The Inner Garden',category:'Mindfulness',price:549,author:'Naina Roy',stock:9},
{id:'SR-004',name:'Stories Under the Banyan',category:'Fiction',price:449,author:'Kabir Sen',stock:21}
];
let cart=JSON.parse(localStorage.getItem('sr_cart')||'[]');
let currentUser=JSON.parse(localStorage.getItem('sr_user')||'null');
const dl=(payload)=>window.dataLayer.push(payload);
function userFields(){return currentUser?{client_id:currentUser.userId,user_type:'loggedin',first_name:currentUser.firstName,hashed_first_name:currentUser.hashedFirstName,last_name:currentUser.lastName,hashed_last_name:currentUser.hashedLastName,email:currentUser.email,hashed_email:currentUser.hashedEmail,phone_number:currentUser.phone,hashed_phone_number:currentUser.hashedPhone}:{client_id:undefined,user_type:'guest',first_name:undefined,hashed_first_name:undefined,last_name:undefined,hashed_last_name:undefined,email:undefined,hashed_email:undefined,phone_number:undefined,hashed_phone_number:undefined};}
function pageType(){return location.hash.startsWith('#product/')?'PDP Page':'Homepage'}
function push(event,extra={}){dl({...userFields(),page_type:pageType(),event,...extra});}
function item(p,index=0,qty=1){return {item_id:p.id,item_name:p.name,affiliation:'Sacred Reads',index,item_brand:'Sacred Reads',item_category:p.category,item_list_id:'home_collection',item_list_name:'Home Collection',price:p.price,quantity:qty};}
function ecommerce(event,items,extra={}){const value=items.reduce((s,x)=>s+x.price*x.quantity,0);dl({ecommerce:null});push(event,{ecommerce:{currency:'INR',value,items,...extra}});}
function render(){document.querySelector('#productGrid').innerHTML=products.map((p,i)=>`<article class="product"><button class="cover" data-view="${p.id}">${p.name}</button><div class="product-info"><h3>${p.name}</h3><p>${p.author} · ${p.category}</p><div class="price-row"><span class="price">₹${p.price}</span><button class="small-btn" data-cart="${p.id}">Add to cart</button></div></div></article>`).join('');ecommerce('view_item_list',products.map((p,i)=>item(p,i)));updateCart();}
function updateCart(){document.querySelector('#cartCount').textContent=cart.reduce((s,x)=>s+x.quantity,0);localStorage.setItem('sr_cart',JSON.stringify(cart));}
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(html){document.querySelector('#modalContent').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden')}
function productById(id){return products.find(p=>p.id===id)}
function viewProduct(id){const p=productById(id);location.hash='product/'+id;ecommerce('view_item',[item(p)]);openModal(`<p class="eyebrow">${p.category}</p><h2 style="font:40px Georgia">${p.name}</h2><p>${p.author}</p><p>A thoughtful addition to your reading shelf. Explore the full description, save it for later, or add it to your cart.</p><h3>₹${p.price}</h3><button class="primary" id="modalAdd">Add to cart</button> <button class="small-btn" id="modalWish">♡ Wishlist</button>`);document.querySelector('#modalAdd').onclick=()=>addCart(p.id);document.querySelector('#modalWish').onclick=()=>{ecommerce('add_to_wishlist',[item(p)]);showToast('Added to wishlist');};}
function addCart(id){const p=productById(id), existing=cart.find(x=>x.id===id);if(existing)existing.quantity++;else cart.push({id,quantity:1});updateCart();ecommerce('add_to_cart',[item(p,0,1)]);showToast(`${p.name} added to cart`);}
function renderCart(){const rows=cart.map(c=>{const p=productById(c.id);return `<div style="display:flex;justify-content:space-between;padding:15px 0;border-bottom:1px solid #e5ddd1"><span><b>${p.name}</b><br>Qty ${c.quantity}</span><span>₹${p.price*c.quantity}</span></div>`}).join('');const items=cart.map(c=>item(productById(c.id),0,c.quantity));const value=items.reduce((s,x)=>s+x.price*x.quantity,0);openModal(`<p class="eyebrow">YOUR CART</p><h2 style="font:36px Georgia">Shopping cart</h2>${rows||'<p>Your cart is empty.</p>'}<h3>Total: ₹${value}</h3>${cart.length?'<button class="primary" id="checkout">Begin checkout</button>':''}`);if(cart.length)document.querySelector('#checkout').onclick=beginCheckout;}
function beginCheckout(){const items=cart.map(c=>item(productById(c.id),0,c.quantity));ecommerce('begin_checkout',items);openModal(`<p class="eyebrow">CHECKOUT</p><h2 style="font:36px Georgia">Complete your order</h2><form id="checkoutForm"><input required placeholder="Full name" style="padding:13px;width:100%;margin:6px 0"><input required type="email" placeholder="Email" style="padding:13px;width:100%;margin:6px 0"><input required placeholder="Shipping address" style="padding:13px;width:100%;margin:6px 0"><select style="padding:13px;width:100%;margin:6px 0"><option>UPI</option><option>Card</option><option>Cash on delivery</option></select><button class="primary" type="submit">Place order</button></form>`);document.querySelector('#checkoutForm').onsubmit=e=>{e.preventDefault();const items=cart.map(c=>item(productById(c.id),0,c.quantity));push('add_shipping_info',{ecommerce:{currency:'INR',value:items.reduce((s,x)=>s+x.price*x.quantity,0),items}});push('add_payment_info',{ecommerce:{currency:'INR',value:items.reduce((s,x)=>s+x.price*x.quantity,0),items}});const transaction='SR-'+Date.now();const value=items.reduce((s,x)=>s+x.price*x.quantity,0);dl({ecommerce:null});push('purchase',{ecommerce:{transaction_id:transaction,currency:'INR',value,shipping:0,tax:0,items}});cart=[];updateCart();openModal(`<p class="eyebrow">ORDER CONFIRMED</p><h2 style="font:42px Georgia">Thank you for your order.</h2><p>Transaction ID: <b>${transaction}</b></p><button class="primary" onclick="closeModal()">Continue shopping</button>`);};}
async function login(){if(currentUser){push('logout');currentUser=null;localStorage.removeItem('sr_user');showToast('Logged out');return;}openModal(`<p class="eyebrow">WELCOME BACK</p><h2 style="font:40px Georgia">Login / Create account</h2><form id="loginForm"><input id="first" required placeholder="First name" style="padding:13px;width:100%;margin:6px 0"><input id="last" required placeholder="Last name" style="padding:13px;width:100%;margin:6px 0"><input id="email" required type="email" placeholder="Email" style="padding:13px;width:100%;margin:6px 0"><input id="phone" required placeholder="Phone" style="padding:13px;width:100%;margin:6px 0"><button class="primary" type="submit">Continue</button></form>`);push('login_initiated');document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const first=firstEl().value,last=lastEl().value,email=emailEl().value,phone=phoneEl().value;const id='SRU-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8).toUpperCase();currentUser={userId:id,firstName:first,lastName:last,email,phone,hashedFirstName:await SacredReadsDataLayer.sha256(first),hashedLastName:await SacredReadsDataLayer.sha256(last),hashedEmail:await SacredReadsDataLayer.sha256(email),hashedPhone:await SacredReadsDataLayer.sha256(phone)};localStorage.setItem('sr_user',JSON.stringify(currentUser));push('login_success',{method:'email'});push('registration_initiated');push('registration_success',{method:'email'});closeModal();showToast('Welcome to Sacred Reads');};}
const firstEl=()=>document.querySelector('#first'),lastEl=()=>document.querySelector('#last'),emailEl=()=>document.querySelector('#email');
document.addEventListener('click',e=>{const m=e.target.closest('[data-menu]');if(m){push('menu_click',{menu_name:m.dataset.menu});document.querySelector('#sideMenu').classList.remove('open');document.querySelector('#overlay').classList.remove('open');}const h=e.target.closest('[data-footer]');if(h)push('footer_click',{footer_link:h.dataset.footer});const v=e.target.closest('[data-view]');if(v)viewProduct(v.dataset.view);const c=e.target.closest('[data-cart]');if(c){push('select_item',{ecommerce:{items:[item(productById(c.dataset.cart))]}});addCart(c.dataset.cart);}});
document.querySelector('#searchForm').onsubmit=e=>{e.preventDefault();const term=document.querySelector('#searchInput').value.trim();if(term){push('search',{search_term:term});showToast(`Searching for “${term}”`);}};
document.querySelector('#loginBtn').onclick=login;document.querySelector('#cartBtn').onclick=renderCart;document.querySelector('#hamburger').onclick=()=>{document.querySelector('#sideMenu').classList.add('open');document.querySelector('#overlay').classList.add('open');push('menu_click',{menu_name:'hamburger'});};document.querySelector('#closeMenu').onclick=()=>{document.querySelector('#sideMenu').classList.remove('open');document.querySelector('#overlay').classList.remove('open')};document.querySelector('#overlay').onclick=document.querySelector('#closeMenu').onclick;document.querySelector('.modal-close').onclick=closeModal;document.querySelector('#shopNow').onclick=()=>document.querySelector('#productGrid').scrollIntoView({behavior:'smooth'});document.querySelector('#viewAll').onclick=()=>{push('menu_click',{menu_name:'view_all'});document.querySelector('#productGrid').scrollIntoView({behavior:'smooth'});};document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();push('newsletter_signup');showToast('You are subscribed!');e.target.reset();};
window.closeModal=closeModal;render();
